---
title       : The Central Limit Theorem (CLT) Demonstration

---



# Help:
*****************************

### Application Input

To use this application, follow these simple steps:

- Select the type of distribution in which the samples are generated from
- The size of each sample (n)
- The number of samples to generate (m)

Hence, there will be m samples of n random variables in total.

For example:
```{r, code}
n <- 30
m <- 300
sampleSize <- n * m
sampleSize
```


As long as the sample size is large enough, the mean computed from these random variable will follow a normal distribution.

In general application, a sample size above 30 iterations is usually considered large enough. In fact, in most cases, as can be seen in the app, even a small sample size of 10 or less would work for some random variables.

*****************************

### Top Plot

Shows the distribution of the samples, as defined by the distribution selected. Noticed that they may not be following the normal distribution, and do not have similarity to that distribution

*****************************

### Bottom Plot

The distribution of the means from each sample follows the theoretical normal distribution (plotted in blue). The distribution follows more closely to the normal distribution, the larger the sample size.

You can observe how the distribution changes as the sample size increases.

*****************************

The source code avaiable on GitHub: [https://github.com/dimacho/ddp_assessment1](https://github.com/dimacho/ddp_assessment1)
